[package]
name = "marketplace-client"
version = "0.1.0"
authors = ["Tomoya Tabuchi <t@tomoyat1.com>"]

[dependencies]
grpc = "0.3.0"
protobuf = "1.5"
futures = "0.1.0"
futures-cpupool = "0.1"
tls-api = "0.1.*"
